export enum Display { None, Inline, Block };

export default {
	ab: Display.Block,
	add: Display.Inline,
	anchor: Display.Inline,
	body: Display.Block,
	cell: Display.Block,
	choice: Display.Inline,
	closer: Display.Block,
	corr: Display.Inline,
	div: Display.Block,
	date: Display.Inline,
	figure: Display.Block,
	formula: Display.Inline,
	geogName: Display.Inline,
	graphic: Display.Block,
	head: Display.Block,
	hi: Display.Inline,
	item: Display.Block,
	l: Display.Block,
	label: Display.Inline,
	lb: Display.Block,
	lg: Display.Block,
	list: Display.Block,
	meta: Display.None,
	name: Display.Inline,
	note: Display.Block,
	opener: Display.Block,
	p: Display.Block,
	pb: Display.None,
	persName: Display.Inline,
	placeName: Display.Inline,
	q: Display.Block,
	row: Display.Block,
	rs: Display.Inline,
	seg: Display.Inline,
	sic: Display.Inline,
	space: Display.Block,
	table: Display.Block,
	text: Display.Block,
	title: Display.Block,
	TEI: Display.Block,
	teiHeader: Display.None,
}